In [2]:
import numpy as np
ar = np.random.rand(2, 3, 5)

In [3]:
np.random.rand( 3, 5)

array([[0.34358013, 0.08871657, 0.69757527, 0.97659612, 0.3782165 ],
       [0.78809291, 0.946025  , 0.3618753 , 0.19865583, 0.18206497],
       [0.47425623, 0.85269427, 0.66634517, 0.54166064, 0.01835848]])

In [4]:
layers = [2,4,5]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
weights

[array([[0.96941619, 0.78018998, 0.81084288, 0.74188474],
        [0.97681943, 0.4013148 , 0.02298782, 0.2238354 ]]),
 array([[0.27170978, 0.21846339, 0.97434825, 0.89063587, 0.11824287],
        [0.60690608, 0.05188647, 0.69235993, 0.99049288, 0.49545776],
        [0.22565899, 0.17554729, 0.45877886, 0.09683823, 0.64467007],
        [0.38720299, 0.27729145, 0.59340718, 0.44072437, 0.23499047]])]

In [5]:
layers[:-1]

[2, 4]

In [6]:
layers[1:]

[4, 5]

In [7]:
for i in ar:
    print(i[1])

[0.96515374 0.26793338 0.08585106 0.49469098 0.67976576]
[0.40305655 0.69350686 0.9019155  0.20857886 0.72585039]


In [8]:
import numpy as np
data = np.array([[0,0,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

X = data[:, :2]
y = data[:, 2:]
activations = []
weights[0]

array([[0.88781088, 0.24324504, 0.02989816, 0.71635855],
       [0.14031827, 0.43519586, 0.16448808, 0.30141411]])

In [9]:
biases[0]

array([[0.09914432, 0.46037754, 0.40386393, 0.74195091]])

In [10]:
z = np.dot(X[0], weights[0])+biases[0]
z

array([[0.09914432, 0.46037754, 0.40386393, 0.74195091]])

In [11]:
import numpy as np
import math

# data = np.array([[0,0,0], [0,1,1], [1,0,1], [1,1,0]])
data = np.array([[0,0,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

def sigmoid(z):
    return 1 / (1+np.exp(z))

def dev_sig(a):
    return a*(1-a)

def output_error(a, y):
    return (a - y) * dev_sig(a)

X = data[:, :2]
y = data[:, 2:]
activations = []
a = X
lr = 0.25
for i in range(0, len(layers)-1):
    z = np.dot(a, weights[i])+biases[i]
    a = sigmoid(z)
    activations.append(a)

for i in range(len(activations)):
    print('activation: ', i)
    print(activations[i])
    print('\n')

n_layers = len(layers)
errors = [output_error(a, y)]
print('Output error: \n', errors)

for idx in range(2, n_layers):
    error = np.dot(errors[0], weights[-idx+1].T)*dev_sig(activations[-idx])
    errors.insert(0, error)

print('\nlayer errors')
for error in errors:
    print(error)
n_data = len(X)
for idx in range(0,n_layers-2):
    weights[idx] = weights[idx] - (lr/n_data)*np.sum(errors[idx]*activations[idx].T)

activation:  0
[[0.29665664 0.29651394 0.48898186 0.44544242]]


activation:  1
[[0.11517567 0.22242319 0.30245893 0.13115252 0.28489386]]


activation:  2
[[0.31118131]]


Output error: 
 [array([[0.06670094]])]

layer errors
[[0.00288278 0.0009743  0.00144853 0.00344997]]
[[0.00183676 0.00798087 0.00772963 0.00023071 0.00266842]]
[[0.06670094]]


In [12]:
len(weights)

3

In [ ]:
n_layers

4

In [59]:
data = np.loadtxt('../data/and_test.csv', delimiter=',', dtype=int)
X = data[:, :-1]
y = data[:, -1] 

dataset = [tuple((X[i], [y[i]])) for i in range(len(X))]

train_size = int(len(dataset) * 0.8)
train_data = dataset[:train_size]
test_data = dataset[train_size:]
train_data[1]

(array([0, 0]), [0])

In [67]:
import random
training_data = train_data.copy()
random.shuffle( training_data )
batches = [ training_data [i:i+ 25 ] for i in range(0, len(train_data),
25 )]
batches[:1]

[[(array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 1]), [1]),
  (array([0, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 0]), [0]),
  (array([1, 1]), [1]),
  (array([0, 0]), [0]),
  (array([1, 1]), [1]),
  (array([1, 0]), [0]),
  (array([0, 1]), [0]),
  (array([0, 1]), [0]),
  (array([1, 1]), [1]),
  (array([0, 0]), [0]),
  (array([0, 1]), [0]),
  (array([1, 1]), [1]),
  (array([0, 0]), [0]),
  (array([0, 1]), [0]),
  (array([1, 1]), [1]),
  (array([0, 1]), [0]),
  (array([1, 1]), [1])]]

In [68]:
for x, y in batches:
    print(x)
    print(y)

ValueError: too many values to unpack (expected 2)