In [1]:
import numpy as np
ar = np.random.rand(2, 3, 5)

In [2]:
np.random.rand( 3, 5)

array([[0.56973106, 0.10598781, 0.60504035, 0.33207616, 0.24212384],
       [0.90582905, 0.5432009 , 0.89351043, 0.32853232, 0.47087217],
       [0.959234  , 0.41619832, 0.26062101, 0.51064112, 0.1994102 ]])

In [3]:
layers = [2,4,5]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
weights

[array([[0.81707434, 0.51104213, 0.53646615, 0.62158423],
        [0.60705271, 0.86532662, 0.43984556, 0.97525424]]),
 array([[0.86145749, 0.7134156 , 0.37423017, 0.68886973, 0.63753122],
        [0.14876325, 0.98320005, 0.32571146, 0.41460782, 0.20724986],
        [0.71941159, 0.18699698, 0.50670145, 0.96741667, 0.25576024],
        [0.97293862, 0.92453398, 0.05653637, 0.19992018, 0.50058754]])]

In [4]:
layers[:-1]

[2, 4]

In [5]:
layers[1:]

[4, 5]

In [6]:
for i in ar:
    print(i[1])

[0.46208318 0.79408754 0.03217862 0.07149077 0.71586344]
[0.52156789 0.93526689 0.06740953 0.65538566 0.8696134 ]


In [7]:
import numpy as np
data = np.array([[0,0,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

X = data[:, :2]
y = data[:, 2:]
activations = []
weights[0]

array([[0.52671464, 0.76371725, 0.21840549, 0.81679978],
       [0.81080873, 0.49623734, 0.82622825, 0.14524143]])

In [8]:
biases[0]

array([[0.80423238, 0.48395506, 0.74312142, 0.53142411]])

In [9]:
z = np.dot(X[0], weights[0])+biases[0]
z

array([[0.80423238, 0.48395506, 0.74312142, 0.53142411]])

In [10]:
import numpy as np
import math

# data = np.array([[0,0,0], [0,1,1], [1,0,1], [1,1,0]])
data = np.array([[0,0,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

def sigmoid(z):
    return 1 / (1+np.exp(z))

def dev_sig(a):
    return a*(1-a)

def output_error(a, y):
    return (a - y) * dev_sig(a)

X = data[:, :2]
y = data[:, 2:]
activations = []
a = X
lr = 0.25
for i in range(0, len(layers)-1):
    z = np.dot(a, weights[i])+biases[i]
    a = sigmoid(z)
    activations.append(a)

for i in range(len(activations)):
    print('activation: ', i)
    print(activations[i])
    print('\n')

n_layers = len(layers)
errors = [output_error(a, y)]
print('Output error: \n', errors)

for idx in range(2, n_layers):
    error = np.dot(errors[0], weights[-idx+1].T)*dev_sig(activations[-idx])
    errors.insert(0, error)

print('\nlayer errors')
for error in errors:
    print(error)
n_data = len(X)
for idx in range(0,n_layers-2):
    weights[idx] = weights[idx] - (lr/n_data)*np.sum(errors[idx]*activations[idx].T)

activation:  0
[[0.37280731 0.49073339 0.43602451 0.38801908]]


activation:  1
[[0.2135246  0.19575532 0.1519858  0.17167954 0.3227526 ]]


activation:  2
[[0.4119946]]


Output error: 
 [array([[0.09980777]])]

layer errors
[[0.00214879 0.00349957 0.00325247 0.00402641]]
[[0.009786   0.00151377 0.00513107 0.00347767 0.00632083]]
[[0.09980777]]


In [11]:
len(weights)

3

In [12]:
n_layers

4

In [27]:
data = np.loadtxt("../data/xor_test.csv", delimiter=',', dtype=int)
X = data[:, :-1]
y = data[:, -1] 

dataset = [(X[i], [y[i]]) for i in range(len(X))]

train_size = int(len(dataset) * 0.8)
train_data = dataset[:train_size]
test_data = dataset[train_size:]
X, y = zip(*test_data)
X

(array([0, 1]),
 array([0, 0]),
 array([1, 1]),
 array([1, 0]),
 array([1, 0]),
 array([0, 0]),
 array([0, 1]),
 array([1, 0]),
 array([0, 0]),
 array([1, 0]),
 array([0, 1]),
 array([1, 0]),
 array([1, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 0]),
 array([1, 0]),
 array([0, 1]),
 array([0, 0]),
 array([0, 0]),
 array([1, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([1, 0]),
 array([1, 0]),
 array([1, 1]),
 array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([1, 0]),
 array([1, 0]),
 array([1, 1]),
 array([0, 0]),
 array([0, 1]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([1, 0]),
 array([0, 0]),
 array([0, 0]),
 array([1, 1]),
 array([1, 1]),
 array([0, 0]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([0, 0]),
 array([0, 1]),
 array([1, 1]),
 array([1, 1]),
 array([1, 1]),
 array([0, 0]),
 array([0, 0]),
 array([