In [14]:
import numpy as np
ar = np.random.rand(2, 3, 5)

In [15]:
np.random.rand( 3, 5)

array([[0.49701927, 0.88879208, 0.5146968 , 0.71899029, 0.35207904],
       [0.05218334, 0.65909457, 0.29890715, 0.65126888, 0.30613362],
       [0.24337945, 0.12478123, 0.98485053, 0.34603927, 0.33522251]])

In [16]:
layers = [2,4,5]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
weights

[array([[0.28210847, 0.26930745, 0.6345684 , 0.33576293],
        [0.67913399, 0.59193711, 0.25134216, 0.32758198]]),
 array([[6.12107138e-01, 4.58781232e-01, 1.57800152e-01, 6.43185941e-01,
         3.41645218e-01],
        [1.52176768e-01, 7.90969557e-01, 6.70077986e-02, 1.09199451e-04,
         4.38062821e-01],
        [5.04659240e-01, 4.19507646e-01, 1.32220489e-01, 5.65172181e-01,
         3.53535735e-01],
        [5.06004564e-01, 9.80602018e-01, 1.87202854e-01, 2.40441094e-02,
         4.36200127e-01]])]

In [17]:
layers[:-1]

[2, 4]

In [18]:
layers[1:]

[4, 5]

In [19]:
for i in ar:
    print(i[1])

[0.49797777 0.49563758 0.39106292 0.34521883 0.13589327]
[0.40445803 0.80207734 0.09713267 0.94211146 0.17611749]


In [20]:
import numpy as np
data = np.array([[0,0,0], [0,1,1], [1,0,1], [1,1,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

X = data[:, :2]
y = data[:, 2:]
activations = []
weights[0]

array([[0.09972441, 0.21688486, 0.46938457, 0.28919163],
       [0.00299905, 0.45538632, 0.60608024, 0.8036408 ]])

In [21]:
biases[0]

array([[0.071818  , 0.50609763, 0.25986277, 0.14919316]])

In [22]:
z = np.dot(X[0], weights[0])+biases[0]
z

array([[0.071818  , 0.50609763, 0.25986277, 0.14919316]])