In [9]:
import numpy as np
ar = np.random.rand(2, 3, 5)

In [14]:
np.random.rand( 3, 5)

array([[0.4741551 , 0.05980618, 0.91418929, 0.08802775, 0.49535472],
       [0.65494662, 0.87361131, 0.84917326, 0.5521557 , 0.56124506],
       [0.15536994, 0.75022381, 0.6597372 , 0.05596126, 0.10684312]])

In [20]:
layers = [2,4,5]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
weights

[array([[0.14441555, 0.79628747, 0.61199865, 0.19330875],
        [0.77126357, 0.15140932, 0.81958365, 0.66983931]]),
 array([[0.46815346, 0.59742422, 0.26056238, 0.15602772, 0.32711535],
        [0.69619168, 0.09013423, 0.40805755, 0.42640263, 0.94642092],
        [0.74280556, 0.00156339, 0.69337951, 0.25748926, 0.97328215],
        [0.37584184, 0.14976177, 0.71035405, 0.89275363, 0.71056901]])]

In [18]:
layers[:-1]

[2, 4]

In [19]:
layers[1:]

[4, 5]

In [12]:
for i in ar:
    print(i[1])

[0.53057685 0.21895895 0.77538022 0.16773538 0.66370533]
[0.20472465 0.90374025 0.54659374 0.66356955 0.11195788]


In [3]:
import numpy as np
data = np.array([[0,0,0], [0,1,1], [1,0,1], [1,1,0]])
layers = [2,4,5,1]
weights = [np.random.rand(x, y) for x, y in zip(layers[:-1], layers[1:])]
biases = [np.random.rand(1, y) for y in layers[1:]]

X = data[:, :2]
y = data[:, 2:]
activations = []
weights[0]

array([[0.59204003, 0.19184424, 0.7975799 , 0.07816532],
       [0.1112072 , 0.11026651, 0.75166682, 0.80019196]])

In [4]:
X[0]

array([0, 0])

In [2]:
z = np.dot(weights[0], X[0])+biases[0]
z

ValueError: shapes (2,4) and (2,) not aligned: 4 (dim 1) != 2 (dim 0)